#!/usr/bin/env sh
set -e

url="https://raw.githubusercontent.com/webuni/shell-task-runner/master/runner"
[ -f ./.runner ] || wget -q "$url" -O- > .runner || curl -fso .runner "$url"
. ./.runner

_decorator()( _decorator_docker_compose_run "$@" )

# Install all dependencies
task_deps()( _run composer install )

# Update dependencies to the latest versions
task_deps__latest()( _run composer update )

# Update dependencies to the lowest versions
task_deps__lowest()( _run composer update --prefer-lowest )

# Run composer
# @service php
task_composer()( composer "$@" )

# Normalize composer.json
# @service php
task_composer__normalize()( composer normalize "$@" )

# Run tests
# @service php
task_tests()( phpunit-8 --colors=always "$@" )

# Fix code style
# @service php
task_cs()( php-cs-fixer fix --ansi --allow-risky=yes "$@" )

# Analyse code
# @service php
task_analyse()( phpstan analyse -l 7 -c phpstan.neon --no-progress --ansi src "$@" )

# Remove all containers in project (use -v to remove volumes also)
task_clean()( _docker_compose down --remove-orphans  "$@" )

# Run shell with tools
# @service php
task_tools()( sh "$@" )
